name = "TropicalYao"
uuid = "8a7e9035-3e12-4286-9ab6-425b4286d857"
authors = ["GiggleLiu"]
version = "0.1.3"

[deps]
BitBasis = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogarithmicNumbers = "aa2f6b4e-9042-5d33-9679-40d3a6b85899"
LuxurySparse = "d05aeea4-b7d4-55ac-b691-9e7fabb07ba2"
NiLang = "ab4ef3a6-0b42-11ea-31f6-e34652774712"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TropicalNumbers = "b3a74e9c-7526-4576-a4eb-79c0d4c32334"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
YaoArrayRegister = "e600142f-9330-5003-8abb-0ebd767abc51"

[compat]
BitBasis = "0.6, 0.7"
LogarithmicNumbers = "0.4"
NiLang = "0.7, 0.8"
StaticArrays = "0.10,0.12"
TropicalNumbers = "0.1, 0.2"
TupleTools = "1.0,1.2"
Yao = "0.6,0.7"
YaoArrayRegister = "0.6,0.7"
LuxurySparse = "0.6"
julia = "1"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ForwardDiff", "Random"]
